version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://test:Digital1@cluster0.d0sdx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - API_URL=http://backend:5000/